[package]

name = "noise"
description = "Procedural noise generation library."
homepage = "https://github.com/bjz/noise-rs"
repository = "https://github.com/bjz/noise-rs"
version = "0.0.3"
license = "Apache-2.0"
keywords = ["math", "random"]
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
           "tiffany352 <https://github.com/tiffany352>",
           "James Miller <james@aatch.net>",
           "Travis Watkins <amaranth@ubuntu.com>",
           "Michael Powell <herufeanor@gmail.com"]

[lib]

name = "noise"

[[example]]

name = "perlin"

[[example]]

name = "open_simplex"

[[example]]

name = "brownian"

[[example]]

name = "cell_range"

[[example]]

name = "cell_range_inv"

[[example]]

name = "cell_value"

[[example]]

name = "cell_manhattan"

[[example]]

name = "cell_manhattan_inv"

[[example]]

name = "cell_manhattan_value"

[[bench]]

name = "benches"

[dev-dependencies.image]

git = "https://github.com/PistonDevelopers/image.git"
